apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: http://localhost:9648
      insecure-skip-tls-verify: true
    name: ocm-mock
contexts:
  - context:
      cluster: ocm-mock
      user: ocm-mock-user
    name: ocm-mock
current-context: ocm-mock
users:
  - name: ocm-mock-user
    user: {}
